export const ADD_COMMENT = 'ADD_COMMENT';

export const PRODUCTOS_LOADING = 'PRODUCTOS_LOADING';
export const ADD_PRODUCTOS = 'ADD_PRODUCTOS';
export const PRODUCTOS_FAILED = 'PRODUCTOS_FAILED';

export const COMENTARIOS_LOADING = 'COMENTARIOS_LOADING';
export const ADD_COMENTARIOS = 'ADD_COMENTARIOS';
export const COMENTARIOS_FAILED = 'COMENTARIOS_FAILED';

export const PROMOCIONES_LOADING = 'PROMOCIONES_LOADING';
export const ADD_PROMOCIONES = 'ADD_PROMOCIONES';
export const PROMOCIONES_FAILED = 'PROMOCIONES_FAILED';


export const ADD_PRODUCTO = 'ADD_PRODUCTO';
export const DELETE_PRODUCTO = 'DELETE_PRODUCTO';
export const ESTADO_CARRITO = 'ESTADO_CARRITO';

export const PRODUCTOUNICO_LOADING = 'PRODUCTOUNICO_LOADING';
export const ADD_PRODUCTOUNICO = 'ADD_PRODUCTOUNICO';
export const PRODUCTOUNICO_FAILED = 'PRODUCTOUNICO_FAILED';

export const VER_POPUP = 'VER_POPUP';
//export const OCULTAR_POPUP = 'OCULTAR_POPUP';