export const ADD_COMMENT = 'ADD_COMMENT';

export const PRODUCTOS_LOADING = 'PRODUCTOS_LOADING';
export const PRODUCTOS_FAILED = 'PRODUCTOS_FAILED';
export const ADD_PRODUCTOS = 'ADD_PRODUCTOS';

export const ADD_COMENTARIOS = 'ADD_COMENTARIOS';
export const COMENTARIOS_FAILED = 'COMENTARIOS_FAILED';

export const PROMOCIONES_LOADING = 'PROMOCIONES_LOADING';
export const ADD_PROMOCIONES = 'ADD_PROMOCIONES';
export const PROMOCIONES_FAILED = 'PROMOCIONES_FAILED';